### ISSUE TITLE
There are two signals in 2008/03-2009/06?

### ISSUE THREAD

**Issue by leonlee723** [ntrang086/rule_based_trading#1]
hi ntrang086
    I run your demo code. But I get only two signals in  2008/03-2009/06. 2008/03/27 is sell signal and 2009/06/02 is buy signal. Is the right? Thank you!

**Comment by ntrang086** [comment]
Hi there,
Which code did you run? best_strategy.py or rule_based_test.ipynb? 
Which data set did you use? Directly from Yahoo finance or http://quantsoftware.gatech.edu/images/a/af/ML4T_2017Fall.zip?
Use the latter zipped data file and run it using rule_based_test.ipynb to compare your results with mine.
